inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false